### ISSUE TITLE
Automatic install does not work on localhost

### ISSUE THREAD

**Issue by rezeau** [rwthanalytics/moodle-logstore_lanalytics#1]
Hi there!
Here is a list of installation results for this plugin (and its associated plugin local_learning_analytics) when clicking the Install Now button in the Moodle plugins repo:
- on my online Moodle site: OK
- _on my localhost Moodle site: Nothing happens_
- please not that on my localhost Moodle site I am able to download both plugins and copy them to the relevant Moodle folders and it works OK.
Details of my localhost: Windows 10, XAMPP installation
Both local and online: Moodle 3.11.2 (Build: 20210729)

**Comment by thomasdondorf** [comment]
This probably has to do with your development environment and is not related to this plugin.

In case you are sure this is related to this plugin, feel free to reopen.
