### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by uaiblaine** [rwthanalytics/moodle-logstore_lanalytics#2]
Testing the plugin with the latest version of Moodle 3.11.6+ and PHP 8.0 the debug reported the error:

`FastCGI sent in stderr: "PHP message: PHP Fatal error: Declaration of logstore_lanalytics\log\store::insert_event_entries(array $events) must be compatible with tool_log\helper\buffered_writer::insert_event_entries($evententries) in /mnt/lab. blaine.com.br/moodle/admin/tool/log/store/lanalytics/classes/log/store.php on line 89`

By changing line 89 in moodle/admin/tool/log/store/lanalytics/classes/log/store.php

from
     `protected function insert_event_entries(array $events) {`
to
    ` protected function insert_event_entries($eventries) {`

solved the problem and apparently did not affect the functioning of the plugin.

**Comment by thomasdondorf** [comment]
Thanks, this will be fixed this week.
